### ISSUE TITLE
Add facet labels/aliases

### ISSUE THREAD

**Issue by rkiesler1** [lucidworks/fusion-financial-demo#8]
Raw Solr field names look pretty bad on this demo:
![image](https://user-images.githubusercontent.com/7738591/56762659-358fac00-6755-11e9-8f2f-365568462ba2.png)

**Comment by davetroiano** [comment]
@rkiesler1 where do you see this?  I'm not finding it on `finance.lucidworks.io` or in the latest 4.2 upgraded app

**Comment by rkiesler1** [comment]
http://finance.lucidworks.io:8780/MarketResearch/#/search?q=mattel (directly from the frequent search link under the search box)

**Comment by davetroiano** [comment]
👍  thanks... this is fixed as part of 4.2 upgrade

**Comment by davetroiano** [comment]
fixed & deployed on finance.lucidworks.io
